/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.brightmind.view;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Poorna
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    
    private StudentPanel studentPanel;
    private SubjectPanel subjectPanel;
    private MarksPanel marksPanel;

    public Dashboard(StudentPanel studentPanel,SubjectPanel subjectPanel, MarksPanel marksPanel) {
        this.studentPanel = studentPanel;
        this.subjectPanel = subjectPanel;
        this.marksPanel = marksPanel;
        initComponents();
        
        viewPanel.add(studentPanel, "studentPanel");
        viewPanel.add(subjectPanel, "subjectPanel");
        viewPanel.add(marksPanel, "marksPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnStudentMng = new javax.swing.JButton();
        btnSubjectMng = new javax.swing.JButton();
        btnMarksMng = new javax.swing.JButton();
        btnUserMng = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("studentFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        jSplitPane1.setDividerLocation(300);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        menuPanel.setPreferredSize(new java.awt.Dimension(300, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g1.png"))); // NOI18N

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(0, 0, 0));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnStudentMng.setBackground(new java.awt.Color(255, 255, 255));
        btnStudentMng.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStudentMng.setForeground(new java.awt.Color(0, 0, 0));
        btnStudentMng.setText("Student Management");
        btnStudentMng.setBorder(null);
        btnStudentMng.setBorderPainted(false);
        btnStudentMng.setContentAreaFilled(false);
        btnStudentMng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudentMng.setFocusPainted(false);
        btnStudentMng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnSubjectMng.setBackground(new java.awt.Color(255, 255, 255));
        btnSubjectMng.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubjectMng.setForeground(new java.awt.Color(0, 0, 0));
        btnSubjectMng.setText("Subject Management");
        btnSubjectMng.setBorder(null);
        btnSubjectMng.setBorderPainted(false);
        btnSubjectMng.setContentAreaFilled(false);
        btnSubjectMng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubjectMng.setFocusPainted(false);
        btnSubjectMng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMarksMng.setBackground(new java.awt.Color(255, 255, 255));
        btnMarksMng.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMarksMng.setForeground(new java.awt.Color(0, 0, 0));
        btnMarksMng.setText("Marks Management");
        btnMarksMng.setBorder(null);
        btnMarksMng.setBorderPainted(false);
        btnMarksMng.setContentAreaFilled(false);
        btnMarksMng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarksMng.setFocusPainted(false);
        btnMarksMng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnUserMng.setBackground(new java.awt.Color(255, 255, 255));
        btnUserMng.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUserMng.setForeground(new java.awt.Color(0, 0, 0));
        btnUserMng.setText("User Management");
        btnUserMng.setBorder(null);
        btnUserMng.setBorderPainted(false);
        btnUserMng.setContentAreaFilled(false);
        btnUserMng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserMng.setFocusPainted(false);
        btnUserMng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(btnUserMng)
                    .addComponent(btnMarksMng)
                    .addComponent(btnSubjectMng)
                    .addComponent(btnStudentMng)
                    .addComponent(btnDashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(btnDashboard)
                .addGap(36, 36, 36)
                .addComponent(btnStudentMng)
                .addGap(37, 37, 37)
                .addComponent(btnSubjectMng)
                .addGap(32, 32, 32)
                .addComponent(btnMarksMng)
                .addGap(33, 33, 33)
                .addComponent(btnUserMng)
                .addGap(27, 27, 27)
                .addComponent(btnLogout)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuPanel);

        viewPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(viewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//    }

    public JButton getBtnMarksMng() {
        return btnMarksMng;
    }

    public JButton getBtnDashboard() {
        return btnDashboard;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnStudentMng() {
        return btnStudentMng;
    }

    public JButton getBtnSubjectMng() {
        return btnSubjectMng;
    }

    public JButton getBtnUserMng() {
        return btnUserMng;
    }
    
    public void switchView(String name) {
        CardLayout cl = (CardLayout) viewPanel.getLayout();
        cl.show(viewPanel, name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarksMng;
    private javax.swing.JButton btnStudentMng;
    private javax.swing.JButton btnSubjectMng;
    private javax.swing.JButton btnUserMng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
